version: '3'
# include:
#   - AuthService/docker-compose.yml
#   - QuestCatalogService/docker-compose.yml
#   - QuestProcessingService/docker-compose.yml
services:
  api-gateway:
    build:
      context: ./ApiGateway
    ports:
      - "80:3000"

  auth-service:
    build:
      context: ./AuthService
    depends_on:
      - db-as

  db-as:
    image: postgres:latest
    # build:
    #   context: ./AuthService/db
    #   dockerfile: as-db.Dockerfile
    environment:
      POSTGRES_DB: as_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    # ports:
    #   - "5433:5432"
    volumes:
      - ./AuthService/db:/docker-entrypoint-initdb.d

  quest-catalog-service:
    build:
      context: ./QuestCatalogService
    depends_on:
      - db-qcs

  db-qcs:
    image: postgres:latest
    # build:
    #   context: ./QuestCatalogService/db
    #   dockerfile: qcs-db.Dockerfile
    environment:
      POSTGRES_DB: qcs_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    # ports:
    #   - "5434:5432"
    volumes:
      - ./QuestCatalogService/db:/docker-entrypoint-initdb.d
  
  quest-processing-service:
    build:
      context: ./QuestProcessingService
    depends_on:
      - db-qps

  db-qps:
    image: postgres:latest
    # build:
    #   context: ./QuestProcessingService/db
    #   dockerfile: qps-db.Dockerfile
    environment:
      POSTGRES_DB: qps_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    # ports:
    #   - "5435:5432"
    volumes:
      - ./QuestProcessingService/db:/docker-entrypoint-initdb.d